// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpZzcDeO9MoYcI2emxpPJsyAmWNN5TnNs',
    appId: '1:199857635319:web:caf8150623f917fcd9f8f2',
    messagingSenderId: '199857635319',
    projectId: 'swachhtaapp-bf94d',
    authDomain: 'swachhtaapp-bf94d.firebaseapp.com',
    storageBucket: 'swachhtaapp-bf94d.appspot.com',
    measurementId: 'G-5NTB5MB60W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT7205fjD_pO4xDOGH1tpUGuhsdcaNPzQ',
    appId: '1:199857635319:android:92f110aad1a5f5bcd9f8f2',
    messagingSenderId: '199857635319',
    projectId: 'swachhtaapp-bf94d',
    storageBucket: 'swachhtaapp-bf94d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpTQMGqQs4oUSi38EZyfF0jPGH9iJ4g3g',
    appId: '1:199857635319:ios:1794cf4bf7e99af0d9f8f2',
    messagingSenderId: '199857635319',
    projectId: 'swachhtaapp-bf94d',
    storageBucket: 'swachhtaapp-bf94d.appspot.com',
    iosBundleId: 'com.example.swachhtaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpTQMGqQs4oUSi38EZyfF0jPGH9iJ4g3g',
    appId: '1:199857635319:ios:1794cf4bf7e99af0d9f8f2',
    messagingSenderId: '199857635319',
    projectId: 'swachhtaapp-bf94d',
    storageBucket: 'swachhtaapp-bf94d.appspot.com',
    iosBundleId: 'com.example.swachhtaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpZzcDeO9MoYcI2emxpPJsyAmWNN5TnNs',
    appId: '1:199857635319:web:d4b489950191abffd9f8f2',
    messagingSenderId: '199857635319',
    projectId: 'swachhtaapp-bf94d',
    authDomain: 'swachhtaapp-bf94d.firebaseapp.com',
    storageBucket: 'swachhtaapp-bf94d.appspot.com',
    measurementId: 'G-7NBRYTQ9NT',
  );

}