// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlDnxLExpXYKnllr62KHjUFCKk2YFJx18',
    appId: '1:437977542583:web:8a4ae840f553ab5e2b0232',
    messagingSenderId: '437977542583',
    projectId: 'swachhta2',
    authDomain: 'swachhta2.firebaseapp.com',
    storageBucket: 'swachhta2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZgfvpS2kkYixytymVwpIR5W6HsjOf_Xo',
    appId: '1:437977542583:android:82a9bb0fea42fdd62b0232',
    messagingSenderId: '437977542583',
    projectId: 'swachhta2',
    storageBucket: 'swachhta2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWKfpofOn6r5LA45e5fTh73iy4eHEdUvc',
    appId: '1:437977542583:ios:6a4f7c2eae1df4432b0232',
    messagingSenderId: '437977542583',
    projectId: 'swachhta2',
    storageBucket: 'swachhta2.appspot.com',
    iosBundleId: 'com.example.swachhtaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWKfpofOn6r5LA45e5fTh73iy4eHEdUvc',
    appId: '1:437977542583:ios:6a4f7c2eae1df4432b0232',
    messagingSenderId: '437977542583',
    projectId: 'swachhta2',
    storageBucket: 'swachhta2.appspot.com',
    iosBundleId: 'com.example.swachhtaApp',
  );
}
